apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: chatbot-8002
  namespace: showroom-{{ .Values.guid }}-{{ .Values.username }}
spec:
  port:
    targetPort: 8002
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: chatbot-8002
    weight: 100