---
apiVersion: v1
kind: Namespace
metadata:
  name: agentic-{{ .Values.username }}
  annotations:
    openshift.io/description: "Agentic AI Namespace"
    openshift.io/display-name: "Workspace"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wksp-edit-{{ .Values.username }}
  namespace: agentic-{{ .Values.username }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.username }}
